### ISSUE TITLE
Ability to add new emulators through the UI

### ISSUE THREAD

**Issue by msmigiel** [GamesomeApp/Gamesome-Frontend#7]
I'm not sure how feasible this is but I'd like to throw it out there.

It would be incredibly helpful to have the ability to add a new emulator automatically through the UI - something like pointing to a custom app that is already installed and then automatically adding it as an emulator for a given system. I don't think long term having hard coded emulators is the way to do as it could quickly make this program obsolete. I already use 2 emulators that aren't in the program and I've tried manually adding them but without luck (another issue logged separately).

**Comment by zevektor** [comment]
Adding emulators is not as easy as choosing an app from a list, you need to reverse engineer the apk to check if the emulator is coded in such a way that external apps can launch games through it. 

Not all developers coded their emulators like this, nor they're interested in doing it. That's why Gamesome and all the other frontends have a list of preset emulators.
